### ISSUE TITLE
Initial setup: non default port is sent as string in json and therefore cannot be unmarshaled to struct in go

### ISSUE THREAD

**Issue by moehringn** [inqueryio/inquery#4]
Using another postgres port sends the frontend json field `port` as a string which leads to an unmarshal error.

**Error: json: cannot unmarshal string into Go struct field ConnConfig.port of type uint16**

Call to http://localhost:3003/api/v1/connection

```
{
    "host": "localhost",
    "port": "5442",
    "database": "postgres",
    "user": "postgres",
    "password": "postgres"
}
```

Leaving the default value, the correct json is submitted:
```
{
    "host": "",
    "port": 5432,
    "database": "postgres",
    "user": "postgres",
    "password": "postgres"
}
```

**Comment by ciminelli** [comment]
Thanks for the report, @moehringn! I just pushed a fix and the new image is available on Docker hub if you can rebuild and try again.

**Comment by moehringn** [comment]
@ciminelli thx, working now
